### DELETE an existing patient entity
#DELETE http://localhost:4000/patient/patients/123e4567-e89b-12d3-a456-426614174000
DELETE http://localhost:4005/gateway/patient/patients/123e4567-e89b-12d3-a456-426614174000
Content-Type: application/json

###
