### GET patient by id
#GET http://localhost:4000/patient/patients/123e4567-e89b-12d3-a456-426614174000
GET http://localhost:4005/gateway/patient/patients/123e4567-e89b-12d3-a456-426614174000
Content-Type: application/json
Authorization: Bearer {{token}}

###